#!/usr/bin/env bash

# PDA Boot Screen color theme.
# Colors use ANSI 256-color escape codes, close to the requested pastel palette.

PDA_ESC="${PDA_ESC:-$'\033'}"
PDA_RESET="${PDA_ESC}[0m"
PDA_BOLD="${PDA_ESC}[1m"
PDA_DIM="${PDA_ESC}[2m"

PDA_LAVENDER="${PDA_ESC}[38;5;183m"      # #C8B6FF
PDA_PINK="${PDA_ESC}[38;5;218m"          # #FFD6E8
PDA_YELLOW="${PDA_ESC}[38;5;229m"        # #FFF0A6
PDA_MINT="${PDA_ESC}[38;5;194m"          # #CFF7D3
PDA_WHITE="${PDA_ESC}[38;5;15m"          # #F8F8FF
PDA_DARK_PURPLE="${PDA_ESC}[38;5;17m"    # #2A203F
PDA_DARK_LAVENDER="${PDA_ESC}[38;5;60m"  # #352A4F
PDA_MOON_PURPLE="${PDA_ESC}[38;5;97m"    # #43335E

PDA_BG_DARK_PURPLE="${PDA_ESC}[48;5;17m"
PDA_BG_DARK_LAVENDER="${PDA_ESC}[48;5;60m"

PDA_ICON_MOON="${PDA_ICON_MOON:-🌙}"
PDA_ICON_STAR="${PDA_ICON_STAR:-✨}"
PDA_ICON_HEART="${PDA_ICON_HEART:-💖}"
PDA_ICON_BOLT="${PDA_ICON_BOLT:-⚡}"
PDA_ICON_CAL="${PDA_ICON_CAL:-📅}"
PDA_ICON_CLOCK="${PDA_ICON_CLOCK:-🕒}"
PDA_ICON_PHONE="${PDA_ICON_PHONE:-📱}"
PDA_ICON_BATTERY="${PDA_ICON_BATTERY:-🔋}"
PDA_ICON_NET="${PDA_ICON_NET:-📡}"
PDA_ICON_PYTHON="${PDA_ICON_PYTHON:-🐍}"
PDA_ICON_NODE="${PDA_ICON_NODE:-🟢}"
PDA_ICON_DISK="${PDA_ICON_DISK:-💾}"
PDA_ICON_RAM="${PDA_ICON_RAM:-🧠}"
PDA_ICON_TEMP="${PDA_ICON_TEMP:-🌡️}"
PDA_ICON_TASK="${PDA_ICON_TASK:-☑️}"
PDA_ICON_POMO="${PDA_ICON_POMO:-🍅}"
